#!/usr/bin/env ruby

require 'yaml'

$hash
$script_name

dash_root = `git rev-parse --show-toplevel`.strip

def question(text)
  $hash[:questions] << { text: text }
end

def style(text)
  $hash[:style] = text
end

def right(text)
  $hash[:answers] << { text: text, correct: true }
end

def wrong(text)
  $hash[:answers] << { text: text, correct: false }
end

def answer(text)
  $hash[:answers] << { text: text }
end

# let's go through all the multis we can find

source = File.expand_path(ARGV.fetch(0, File.join(dash_root, "config", "puzzles/*.multi")))

Dir.glob(source).each do |script|
  $script_name = script.gsub(/.*\/(\w+).multi$/, '\1')
  $stderr.puts $script_name

  $hash = { :questions => [], :answers => [] }

  load script

  $stdout.reopen("#{script}.yml", "w")
  puts $hash.to_yaml

end
